In [1]:
import numpy as np
import pandas as pd
import scanpy as sc
import gc
import sys
import os
sys.path.append('../')
from AIID_notebooks.inflapy.immunoFunc import *

##### Elmentaite_2020

In [2]:
print(sc.__version__)

1.9.1

In [3]:
path="/lustre/scratch117/cellgen/cellgeni/TIC-starsolo/tic-1808/E-MTAB-8901/"

In [4]:
s_path = "/nfs/team205/bh14/Datasets/Remapped/raw_adata/"

In [5]:
#GSE121380/GSM3433578/output/Velocyto/filtered/

pheno = pd.read_csv(s_path+"E-MTAB-8901/pheno.csv")

In [6]:
pheno

,donor_id,arrayExpress,age,sex,disease,tissue,dataset_id,cell_source
0,T176_IL_cells_ERS4414954,ERS4414954,11,male,Crohn's Disease,terminal ileum,Elmentaite_2020,Ileum
1,T189_IL_cells_ERS4414955,ERS4414955,13,female,Crohn's Disease,terminal ileum,Elmentaite_2020,Ileum
2,T197_IL_cells_ERS4414956,ERS4414956,9,male,Crohn's Disease,terminal ileum,Elmentaite_2020,Ileum
3,T202_IL_cells_ERS4414957,ERS4414957,12,female,Crohn's Disease,terminal ileum,Elmentaite_2020,Ileum
4,T203_IL_cells_ERS4414958,ERS4414958,14,male,Crohn's Disease,terminal ileum,Elmentaite_2020,Ileum
5,T017_IL_cells_ERS4414959,ERS4414959,13,male,Crohn's Disease,terminal ileum,Elmentaite_2020,Ileum
6,T019_IL_cells_ERS4414960,ERS4414960,12,male,Crohn's Disease,terminal ileum,Elmentaite_2020,Ileum
7,T024_IL_cells_ERS4414967,ERS4414967,12,female,Healthy,terminal ileum,Elmentaite_2020,Ileum
8,T036_IL_cells_ERS4414968,ERS4414968,4,male,Healthy,terminal ileum,Elmentaite_2020,Ileum
9,T057_IL_cells_ERS4414969,ERS4414969,6,male,Healthy,terminal ileum,Elmentaite_2020,Ileum
10,T110_IL_cells_ERS4414970,ERS4414970,4,male,Healthy,terminal ileum,Elmentaite_2020,Ileum
11,T160_IL_cells_ERS4414971,ERS4414971,10,female,Healthy,terminal ileum,Elmentaite_2020,Ileum
12,T161_IL_cells_ERS4414972,ERS4414972,4,male,Healthy,terminal ileum,Elmentaite_2020,Ileum
13,T182_IL_cells_ERS4414973,ERS4414973,9,male,Healthy,terminal ileum,Elmentaite_2020,Ileum
14,T44_IL_cells_ERS4414974,ERS4414974,10,female,Healthy,terminal ileum,Elmentaite_2020,Ileum

##### Immune compartment

In [7]:
for i in range(pheno.shape[0]):
    samp = pheno.arrayExpress[i]
    print("Processing "+samp)
    adata = sc.read_10x_mtx(path+samp+"/output/Gene/filtered/")

    #adata.var[['ensembl', 'gene_symbol']]
    
    adata.obs["dataset_id"] = pheno.dataset_id[i]
    adata.obs["donor_id"] = pheno.donor_id[i]
    adata.obs["tissue"] = pheno.tissue[i]
    adata.obs["cell_source"] = pheno.cell_source[i]
    adata.obs["disease"] = pheno.disease[i]
    adata.obs["age"] = pheno.age[i]
    adata.obs["sex"] = pheno.sex[i]
    adata.obs["development_stage"] = "Paediatric"
    
    if 'adata_conc' in locals():
        adata.var_names_make_unique()
        adata_conc.var_names_make_unique()
        adata_conc = sc.concat([adata,adata_conc], index_unique="-")
        
    else:
        adata_conc = adata

    print(adata_conc.shape)

Processing ERS4414954
(14058, 36601)
Processing ERS4414955
(15458, 36601)
Processing ERS4414956
(21805, 36601)
Processing ERS4414957
(27062, 36601)
Processing ERS4414958
(30083, 36601)
Processing ERS4414959
(36462, 36601)
Processing ERS4414960
(41381, 36601)
Processing ERS4414967
(44989, 36601)
Processing ERS4414968
(52149, 36601)
Processing ERS4414969
(59284, 36601)
Processing ERS4414970
(62981, 36601)
Processing ERS4414971
(65501, 36601)
Processing ERS4414972
(67227, 36601)
Processing ERS4414973
(70794, 36601)
Processing ERS4414974
(73614, 36601)

In [8]:
adata_conc.obs

,dataset_id,donor_id,tissue,cell_source,disease,age,sex,development_stage
AAACCTGAGACCACGA-0,Elmentaite_2020,T44_IL_cells_ERS4414974,terminal ileum,Ileum,Healthy,10,female,Paediatric
AAACCTGAGGTGTGGT-0,Elmentaite_2020,T44_IL_cells_ERS4414974,terminal ileum,Ileum,Healthy,10,female,Paediatric
AAACCTGAGTATCTCG-0,Elmentaite_2020,T44_IL_cells_ERS4414974,terminal ileum,Ileum,Healthy,10,female,Paediatric
AAACCTGAGTCCAGGA-0,Elmentaite_2020,T44_IL_cells_ERS4414974,terminal ileum,Ileum,Healthy,10,female,Paediatric
AAACCTGCATCGGACC-0,Elmentaite_2020,T44_IL_cells_ERS4414974,terminal ileum,Ileum,Healthy,10,female,Paediatric
...,...,...,...,...,...,...,...,...
TTTGTCATCCGTCATC-1-1-1-1-1-1-1-1-1-1-1-1-1-1,Elmentaite_2020,T176_IL_cells_ERS4414954,terminal ileum,Ileum,Crohn's Disease,11,male,Paediatric
TTTGTCATCGTACCGG-1-1-1-1-1-1-1-1-1-1-1-1-1-1,Elmentaite_2020,T176_IL_cells_ERS4414954,terminal ileum,Ileum,Crohn's Disease,11,male,Paediatric
TTTGTCATCTAAGCCA-1-1-1-1-1-1-1-1-1-1-1-1-1-1,Elmentaite_2020,T176_IL_cells_ERS4414954,terminal ileum,Ileum,Crohn's Disease,11,male,Paediatric
TTTGTCATCTATCCCG-1-1-1-1-1-1-1-1-1-1-1-1-1-1,Elmentaite_2020,T176_IL_cells_ERS4414954,terminal ileum,Ileum,Crohn's Disease,11,male,Paediatric
TTTGTCATCTTCCTTC-1-1-1-1-1-1-1-1-1-1-1-1-1-1,Elmentaite_2020,T176_IL_cells_ERS4414954,terminal ileum,Ileum,Crohn's Disease,11,male,Paediatric

In [9]:
adata_conc.write_h5ad(s_path+"Tissue_or_Nonimmune/Elmentaite_2020_Ileum_Paediatric.h5ad")

In [10]:
adata_conc.obs["disease"].value_counts()

Crohn's Disease    41381
Healthy            32233
Name: disease, dtype: int64