In [1]:
import numpy as np
import pandas as pd
import scanpy as sc
import gc
import sys
import os
sys.path.append('../')
from AIID_notebooks.inflapy.immunoFunc import *

##### GSE134809_Martin_et_al_2019

In [2]:
print(sc.__version__)

1.9.1

In [3]:
path="/warehouse/cellgeni/tic-1168/GSE134809/"

In [4]:
s_path = "/nfs/team205/bh14/Datasets/Remapped/raw_adata/"

In [5]:
#GSE121380/GSM3433578/output/Velocyto/filtered/

pheno = pd.read_csv(s_path+"GSE134809/pheno.csv")

In [6]:
pheno

,donor_id,tissue,disease,dataset_id,cell_source
0,GSM3972009,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
1,GSM3972010,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
2,GSM3972011,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
3,GSM3972012,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
4,GSM3972013,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
5,GSM3972014,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
6,GSM3972015,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
7,GSM3972016,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
8,GSM3972017,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
9,GSM3972018,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
10,GSM3972019,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
11,GSM3972020,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
12,GSM3972021,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
13,GSM3972022,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
14,GSM3972023,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
15,GSM3972024,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
16,GSM3972025,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
17,GSM3972026,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
18,GSM3972027,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
19,GSM3972028,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
20,GSM3972029,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
21,GSM3972030,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
22,GSM4761136,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC
23,GSM4761137,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC
24,GSM4761138,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC
25,GSM4761139,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC
26,GSM4761140,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC
27,GSM4761141,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC
28,GSM4761142,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC
29,GSM4761143,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC
30,GSM4761144,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC

##### Immune compartment

In [7]:
#only immune compartments
pheno_immune = pheno[pheno['tissue']=='Blood']
pheno_immune.reset_index(inplace=True)
pheno_immune

,index,donor_id,tissue,disease,dataset_id,cell_source
0,22,GSM4761136,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC
1,23,GSM4761137,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC
2,24,GSM4761138,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC
3,25,GSM4761139,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC
4,26,GSM4761140,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC
5,27,GSM4761141,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC
6,28,GSM4761142,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC
7,29,GSM4761143,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC
8,30,GSM4761144,Blood,Crohn's disease,GSE134809_Martin_et_al_2019,PBMC

In [8]:
dataset="GSE134809/"

In [9]:
for i in range(pheno_immune.shape[0]):
    samp = pheno_immune.donor_id[i]
    print("Processing "+samp)
    adata = sc.read_mtx(path+samp+"/output/Gene/filtered/matrix.mtx.gz")

    var_names = np.genfromtxt(path+samp+"/output/Gene/filtered/genes.tsv.gz",dtype=str)
    var_names


    var_names[:,0]

        #print('observation names...')
    obs_names = np.genfromtxt(path+samp+"/output/Gene/filtered/barcodes.tsv.gz",dtype=str)
    obs_names

    obs_names.shape

    adata = adata.transpose()

    adata.var_names = var_names[:,1]
    adata.obs_names = obs_names

    adata.var_names_make_unique()

    adata.var[['ensembl', 'gene_symbol']] = var_names[:,0:2]
    
    adata.obs["dataset_id"] = pheno_immune.dataset_id[i]
    adata.obs["donor_id"] = pheno_immune.donor_id[i]
    adata.obs["tissue"] = pheno_immune.tissue[i]
    adata.obs["cell_source"] = pheno_immune.cell_source[i]
    adata.obs["disease"] = pheno_immune.disease[i]
    
    if 'adata_conc' in locals():
        adata.var_names_make_unique()
        adata_conc.var_names_make_unique()
        adata_conc = sc.concat([adata,adata_conc], index_unique="-")
        
    else:
        adata_conc = adata

    print(adata_conc.shape)

Processing GSM4761136
(2024, 36601)
Processing GSM4761137
(4176, 36601)
Processing GSM4761138
(5392, 36601)
Processing GSM4761139
(6796, 36601)
Processing GSM4761140
(9969, 36601)
Processing GSM4761141
(14390, 36601)
Processing GSM4761142
(20316, 36601)
Processing GSM4761143
(21529, 36601)
Processing GSM4761144
(26855, 36601)

In [10]:
adata_conc

AnnData object with n_obs × n_vars = 26855 × 36601
    obs: 'dataset_id', 'donor_id', 'tissue', 'cell_source', 'disease'

In [11]:
adata_conc.write_h5ad(s_path+"Immune_compartment/GSE134809_Martin_et_al_2019_PBMC.h5ad")

##### Non immune: Ileum

In [12]:
del adata_conc
del adata
gc.collect()

1265

In [13]:
#only immune compartments
pheno_nonimmune = pheno[pheno['tissue']!='Blood']
pheno_nonimmune.reset_index(inplace=True)

In [14]:
pheno_nonimmune

,index,donor_id,tissue,disease,dataset_id,cell_source
0,0,GSM3972009,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
1,1,GSM3972010,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
2,2,GSM3972011,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
3,3,GSM3972012,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
4,4,GSM3972013,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
5,5,GSM3972014,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
6,6,GSM3972015,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
7,7,GSM3972016,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
8,8,GSM3972017,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
9,9,GSM3972018,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
10,10,GSM3972019,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
11,11,GSM3972020,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
12,12,GSM3972021,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
13,13,GSM3972022,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
14,14,GSM3972023,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
15,15,GSM3972024,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
16,16,GSM3972025,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
17,17,GSM3972026,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
18,18,GSM3972027,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
19,19,GSM3972028,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum
20,20,GSM3972029,Ileum,Uninflamed CD,GSE134809_Martin_et_al_2019,Ileum
21,21,GSM3972030,Ileum,Crohn's disease,GSE134809_Martin_et_al_2019,Ileum

In [15]:
for i in range(pheno_nonimmune.shape[0]):
    samp = pheno_nonimmune.donor_id[i]
    print("Processing "+samp)
    adata = sc.read_mtx(path+samp+"/output/Gene/filtered/matrix.mtx.gz")

    var_names = np.genfromtxt(path+samp+"/output/Gene/filtered/genes.tsv.gz",dtype=str)
    var_names


    var_names[:,0]

        #print('observation names...')
    obs_names = np.genfromtxt(path+samp+"/output/Gene/filtered/barcodes.tsv.gz",dtype=str)
    obs_names

    obs_names.shape

    adata = adata.transpose()

    adata.var_names = var_names[:,1]
    adata.obs_names = obs_names

    adata.var_names_make_unique()

    adata.var[['ensembl', 'gene_symbol']] = var_names[:,0:2]
    
    adata.obs["dataset_id"] = pheno_nonimmune.dataset_id[i]
    adata.obs["donor_id"] = pheno_nonimmune.donor_id[i]
    adata.obs["tissue"] = pheno_nonimmune.tissue[i]
    adata.obs["cell_source"] = pheno_nonimmune.cell_source[i]
    adata.obs["disease"] = pheno_nonimmune.disease[i]
    
    if 'adata_conc' in locals():
        adata.var_names_make_unique()
        adata_conc.var_names_make_unique()
        adata_conc = sc.concat([adata,adata_conc], index_unique="-")
        
    else:
        adata_conc = adata

    print(adata_conc.shape)

Processing GSM3972009
(3700, 36601)
Processing GSM3972010
(14084, 36601)
Processing GSM3972011
(15604, 36601)
Processing GSM3972012
(18310, 36601)
Processing GSM3972013
(21534, 36601)
Processing GSM3972014
(24280, 36601)
Processing GSM3972015
(28850, 36601)
Processing GSM3972016
(33339, 36601)
Processing GSM3972017
(38824, 36601)
Processing GSM3972018
(44831, 36601)
Processing GSM3972019
(48526, 36601)
Processing GSM3972020
(56363, 36601)
Processing GSM3972021
(59477, 36601)
Processing GSM3972022
(61138, 36601)
Processing GSM3972023
(66587, 36601)
Processing GSM3972024
(72209, 36601)
Processing GSM3972025
(76871, 36601)
Processing GSM3972026
(84486, 36601)
Processing GSM3972027
(89011, 36601)
Processing GSM3972028
(93105, 36601)
Processing GSM3972029
(96936, 36601)
Processing GSM3972030
(102215, 36601)

In [18]:
adata_conc.obs.disease.value_counts()

Uninflamed CD      51689
Crohn's disease    50526
Name: disease, dtype: int64

In [19]:
adata_conc.write_h5ad(s_path+"Tissue_or_Nonimmune/GSE134809_Martin_et_al_2019_Ileum.h5ad")