In [1]:
import numpy as np
import pandas as pd
import scanpy as sc
import gc
import sys
import os
sys.path.append('../')
from AIID_notebooks.inflapy.immunoFunc import *

##### GSE163314_Lefferts_2021

In [2]:
print(sc.__version__)

1.9.1

In [3]:
path="/lustre/scratch117/cellgen/cellgeni/TIC-starsolo/tic-1808/GSE163314/"

In [4]:
s_path = "/nfs/team205/bh14/Datasets/Remapped/raw_adata/"

In [5]:
#GSE121380/GSM3433578/output/Velocyto/filtered/

pheno = pd.read_csv(s_path+"GSE163314/pheno.csv")

In [6]:
pheno

,donor_id,geo_accession,tissue,disease,dataset_id,cell_source
0,Patient_2_Colon_GSM4976992,GSM4976992,Retrosigmoid Colon,CD + Spondyloarthritis,GSE163314_Lefferts_2021,Colon
1,Patient_2_Blood_GSM4976993,GSM4976993,Blood,CD + Spondyloarthritis,GSE163314_Lefferts_2021,PBMC
2,Patient_3_Colon_GSM4976994,GSM4976994,Retrosigmoid Colon,Spondyloarhtritis,GSE163314_Lefferts_2021,Colon
3,Patient_3_Blood_GSM4976995,GSM4976995,Blood,Spondyloarhtritis,GSE163314_Lefferts_2021,PBMC
4,Patient_5_Colon_GSM4976996,GSM4976996,Retrosigmoid Colon,Healthy,GSE163314_Lefferts_2021,Colon
5,Patient_5_Blood_GSM4976997,GSM4976997,Blood,Healthy,GSE163314_Lefferts_2021,PBMC
6,Patient_7_Colon_GSM4976998,GSM4976998,Retrosigmoid Colon,Crohn's Disease,GSE163314_Lefferts_2021,Colon
7,Patient_7_Blood_GSM4976999,GSM4976999,Blood,Crohn's Disease,GSE163314_Lefferts_2021,PBMC
8,Patient_21_Colon_GSM4977000,GSM4977000,Retrosigmoid Colon,Healthy,GSE163314_Lefferts_2021,Colon
9,Patient_21_Blood_GSM4977001,GSM4977001,Blood,Healthy,GSE163314_Lefferts_2021,PBMC
10,Patient_23_Colon_GSM4977002,GSM4977002,Retrosigmoid Colon,Crohn's Disease,GSE163314_Lefferts_2021,Colon
11,Patient_23_Blood_GSM4977003,GSM4977003,Blood,Crohn's Disease,GSE163314_Lefferts_2021,PBMC
12,Patient_27_Colon_GSM4977004,GSM4977004,Retrosigmoid Colon,Spondyloarhtritis,GSE163314_Lefferts_2021,Colon
13,Patient_27_Blood_GSM4977005,GSM4977005,Blood,Spondyloarhtritis,GSE163314_Lefferts_2021,PBMC
14,Patient_33_Colon_GSM4977006,GSM4977006,Retrosigmoid Colon,CD + Spondyloarthritis,GSE163314_Lefferts_2021,Colon
15,Patient_33_Blood_GSM4977007,GSM4977007,Blood,CD + Spondyloarthritis,GSE163314_Lefferts_2021,PBMC

In [7]:
pheno1 = pheno[pheno.cell_source=="PBMC"]
pheno1.reset_index(inplace=True)

In [8]:
pheno1

,index,donor_id,geo_accession,tissue,disease,dataset_id,cell_source
0,1,Patient_2_Blood_GSM4976993,GSM4976993,Blood,CD + Spondyloarthritis,GSE163314_Lefferts_2021,PBMC
1,3,Patient_3_Blood_GSM4976995,GSM4976995,Blood,Spondyloarhtritis,GSE163314_Lefferts_2021,PBMC
2,5,Patient_5_Blood_GSM4976997,GSM4976997,Blood,Healthy,GSE163314_Lefferts_2021,PBMC
3,7,Patient_7_Blood_GSM4976999,GSM4976999,Blood,Crohn's Disease,GSE163314_Lefferts_2021,PBMC
4,9,Patient_21_Blood_GSM4977001,GSM4977001,Blood,Healthy,GSE163314_Lefferts_2021,PBMC
5,11,Patient_23_Blood_GSM4977003,GSM4977003,Blood,Crohn's Disease,GSE163314_Lefferts_2021,PBMC
6,13,Patient_27_Blood_GSM4977005,GSM4977005,Blood,Spondyloarhtritis,GSE163314_Lefferts_2021,PBMC
7,15,Patient_33_Blood_GSM4977007,GSM4977007,Blood,CD + Spondyloarthritis,GSE163314_Lefferts_2021,PBMC

##### Immune compartment

In [9]:
for i in range(pheno1.shape[0]):
    samp = pheno1.geo_accession[i]
    print("Processing "+samp)
    adata = sc.read_10x_mtx(path+samp+"/output/Gene/filtered/")

    #adata.var[['ensembl', 'gene_symbol']]
    
    adata.obs["dataset_id"] = pheno1.dataset_id[i]
    adata.obs["donor_id"] = pheno1.donor_id[i]
    adata.obs["tissue"] = pheno1.tissue[i]
    adata.obs["cell_source"] = pheno1.cell_source[i]
    adata.obs["disease"] = pheno1.disease[i]
    
    if 'adata_conc' in locals():
        adata.var_names_make_unique()
        adata_conc.var_names_make_unique()
        adata_conc = sc.concat([adata,adata_conc], index_unique="-")
        
    else:
        adata_conc = adata

    print(adata_conc.shape)

Processing GSM4976993
(5164, 36601)
Processing GSM4976995
(11621, 36601)
Processing GSM4976997
(19295, 36601)
Processing GSM4976999
(26242, 36601)
Processing GSM4977001
(30216, 36601)
Processing GSM4977003
(42552, 36601)
Processing GSM4977005
(48975, 36601)
Processing GSM4977007
(53037, 36601)

In [10]:
adata_conc

AnnData object with n_obs × n_vars = 53037 × 36601
    obs: 'dataset_id', 'donor_id', 'tissue', 'cell_source', 'disease'

In [11]:
adata_conc.write_h5ad(s_path+"Immune_compartment/GSE163314_Lefferts_2021_PBMC.h5ad")

##### Colon

In [12]:
del adata_conc
del adata
gc.collect()

1037

In [13]:
pheno1 = pheno[pheno.cell_source!="PBMC"]
pheno1.reset_index(inplace=True)

In [14]:
pheno1

,index,donor_id,geo_accession,tissue,disease,dataset_id,cell_source
0,0,Patient_2_Colon_GSM4976992,GSM4976992,Retrosigmoid Colon,CD + Spondyloarthritis,GSE163314_Lefferts_2021,Colon
1,2,Patient_3_Colon_GSM4976994,GSM4976994,Retrosigmoid Colon,Spondyloarhtritis,GSE163314_Lefferts_2021,Colon
2,4,Patient_5_Colon_GSM4976996,GSM4976996,Retrosigmoid Colon,Healthy,GSE163314_Lefferts_2021,Colon
3,6,Patient_7_Colon_GSM4976998,GSM4976998,Retrosigmoid Colon,Crohn's Disease,GSE163314_Lefferts_2021,Colon
4,8,Patient_21_Colon_GSM4977000,GSM4977000,Retrosigmoid Colon,Healthy,GSE163314_Lefferts_2021,Colon
5,10,Patient_23_Colon_GSM4977002,GSM4977002,Retrosigmoid Colon,Crohn's Disease,GSE163314_Lefferts_2021,Colon
6,12,Patient_27_Colon_GSM4977004,GSM4977004,Retrosigmoid Colon,Spondyloarhtritis,GSE163314_Lefferts_2021,Colon
7,14,Patient_33_Colon_GSM4977006,GSM4977006,Retrosigmoid Colon,CD + Spondyloarthritis,GSE163314_Lefferts_2021,Colon

##### Immune compartment

In [15]:
for i in range(pheno1.shape[0]):
    samp = pheno1.geo_accession[i]
    print("Processing "+samp)
    adata = sc.read_10x_mtx(path+samp+"/output/Gene/filtered/")

    #adata.var[['ensembl', 'gene_symbol']]
    
    adata.obs["dataset_id"] = pheno1.dataset_id[i]
    adata.obs["donor_id"] = pheno1.donor_id[i]
    adata.obs["tissue"] = pheno1.tissue[i]
    adata.obs["cell_source"] = pheno1.cell_source[i]
    adata.obs["disease"] = pheno1.disease[i]
    
    if 'adata_conc' in locals():
        adata.var_names_make_unique()
        adata_conc.var_names_make_unique()
        adata_conc = sc.concat([adata,adata_conc], index_unique="-")
        
    else:
        adata_conc = adata

    print(adata_conc.shape)

Processing GSM4976992
(1133, 36601)
Processing GSM4976994
(1622, 36601)
Processing GSM4976996
(2110, 36601)
Processing GSM4976998
(2639, 36601)
Processing GSM4977000
(5426, 36601)
Processing GSM4977002
(9427, 36601)
Processing GSM4977004
(12954, 36601)
Processing GSM4977006
(14559, 36601)

In [16]:
adata_conc.obs

,dataset_id,donor_id,tissue,cell_source,disease
AAACCTGCACCACGTG-0,GSE163314_Lefferts_2021,Patient_33_Colon_GSM4977006,Retrosigmoid Colon,Colon,CD + Spondyloarthritis
AAACCTGCAGGGTTAG-0,GSE163314_Lefferts_2021,Patient_33_Colon_GSM4977006,Retrosigmoid Colon,Colon,CD + Spondyloarthritis
AAACCTGTCACTTACT-0,GSE163314_Lefferts_2021,Patient_33_Colon_GSM4977006,Retrosigmoid Colon,Colon,CD + Spondyloarthritis
AAACCTGTCGGCTTGG-0,GSE163314_Lefferts_2021,Patient_33_Colon_GSM4977006,Retrosigmoid Colon,Colon,CD + Spondyloarthritis
AAACGGGAGCACCGTC-0,GSE163314_Lefferts_2021,Patient_33_Colon_GSM4977006,Retrosigmoid Colon,Colon,CD + Spondyloarthritis
...,...,...,...,...,...
TTTGGTTCATCATCCC-1-1-1-1-1-1-1,GSE163314_Lefferts_2021,Patient_2_Colon_GSM4976992,Retrosigmoid Colon,Colon,CD + Spondyloarthritis
TTTGTCAAGTGGTCCC-1-1-1-1-1-1-1,GSE163314_Lefferts_2021,Patient_2_Colon_GSM4976992,Retrosigmoid Colon,Colon,CD + Spondyloarthritis
TTTGTCAGTGATGCCC-1-1-1-1-1-1-1,GSE163314_Lefferts_2021,Patient_2_Colon_GSM4976992,Retrosigmoid Colon,Colon,CD + Spondyloarthritis
TTTGTCAGTGCCTGCA-1-1-1-1-1-1-1,GSE163314_Lefferts_2021,Patient_2_Colon_GSM4976992,Retrosigmoid Colon,Colon,CD + Spondyloarthritis
TTTGTCATCGCCGTGA-1-1-1-1-1-1-1,GSE163314_Lefferts_2021,Patient_2_Colon_GSM4976992,Retrosigmoid Colon,Colon,CD + Spondyloarthritis

In [17]:
adata_conc.write_h5ad(s_path+"Tissue_or_Nonimmune/GSE163314_Lefferts_2021_Colon.h5ad")