In [1]:
import numpy as np
import pandas as pd
import scanpy as sc
import gc
import sys
import os
sys.path.append('../')
from AIID_notebooks.inflapy.immunoFunc import *

##### GSE176308_Nanus_2021

In [2]:
print(sc.__version__)

1.9.1

In [3]:
path="/lustre/scratch117/cellgen/cellgeni/alexp/for_Lesha/GSM_to_SRR/done_starsolo/GSE176308/"

In [4]:
s_path = "/nfs/team205/bh14/Datasets/Remapped/raw_adata/"

In [5]:
#GSE121380/GSM3433578/output/Velocyto/filtered/

pheno = pd.read_csv(s_path+"GSE176308/pheno.csv")

In [6]:
pheno

,donor_id,geo_accession,cell_source,disease,tissue,dataset_id
0,EndStage_OA_painful_GSM5362559,GSM5362559,Synovial fibroblasts,Osteoarthritis,Synovial tissue,GSE176308_Nanus_2021
1,Early_OA_painful_GSM5362560,GSM5362560,Synovial fibroblasts,Osteoarthritis,Synovial tissue,GSE176308_Nanus_2021
2,Early_OA_non-painful_GSM5362561,GSM5362561,Synovial fibroblasts,Osteoarthritis,Synovial tissue,GSE176308_Nanus_2021

##### Immune compartment

In [7]:
for i in range(pheno.shape[0]):
    samp = pheno.geo_accession[i]
    print("Processing "+samp)
    adata = sc.read_10x_mtx(path+samp+"/output/Gene/filtered/")

    #adata.var[['ensembl', 'gene_symbol']]
    
    adata.obs["dataset_id"] = pheno.dataset_id[i]
    adata.obs["donor_id"] = pheno.donor_id[i]
    adata.obs["tissue"] = pheno.tissue[i]
    adata.obs["cell_source"] = pheno.cell_source[i]
    adata.obs["disease"] = pheno.disease[i]
    
    if 'adata_conc' in locals():
        adata.var_names_make_unique()
        adata_conc.var_names_make_unique()
        adata_conc = sc.concat([adata,adata_conc], index_unique="-")
        
    else:
        adata_conc = adata

    print(adata_conc.shape)

Processing GSM5362559
(1446, 36601)
Processing GSM5362560
(3120, 36601)
Processing GSM5362561
(4248, 36601)

In [8]:
adata_conc.obs

,dataset_id,donor_id,tissue,cell_source,disease
AAACCTGAGCTCTCGG-0,GSE176308_Nanus_2021,Early_OA_non-painful_GSM5362561,Synovial tissue,Synovial fibroblasts,Osteoarthritis
AAACCTGGTCCTCCAT-0,GSE176308_Nanus_2021,Early_OA_non-painful_GSM5362561,Synovial tissue,Synovial fibroblasts,Osteoarthritis
AAACCTGGTGCACGAA-0,GSE176308_Nanus_2021,Early_OA_non-painful_GSM5362561,Synovial tissue,Synovial fibroblasts,Osteoarthritis
AAACCTGTCAGATAAG-0,GSE176308_Nanus_2021,Early_OA_non-painful_GSM5362561,Synovial tissue,Synovial fibroblasts,Osteoarthritis
AAACGGGAGCGATAGC-0,GSE176308_Nanus_2021,Early_OA_non-painful_GSM5362561,Synovial tissue,Synovial fibroblasts,Osteoarthritis
...,...,...,...,...,...
TTTGGTTAGTGGCACA-1-1,GSE176308_Nanus_2021,EndStage_OA_painful_GSM5362559,Synovial tissue,Synovial fibroblasts,Osteoarthritis
TTTGGTTCATAAAGGT-1-1,GSE176308_Nanus_2021,EndStage_OA_painful_GSM5362559,Synovial tissue,Synovial fibroblasts,Osteoarthritis
TTTGGTTGTAAGGGCT-1-1,GSE176308_Nanus_2021,EndStage_OA_painful_GSM5362559,Synovial tissue,Synovial fibroblasts,Osteoarthritis
TTTGTCAAGCGTTGCC-1-1,GSE176308_Nanus_2021,EndStage_OA_painful_GSM5362559,Synovial tissue,Synovial fibroblasts,Osteoarthritis
TTTGTCAGTAGCGTCC-1-1,GSE176308_Nanus_2021,EndStage_OA_painful_GSM5362559,Synovial tissue,Synovial fibroblasts,Osteoarthritis

In [9]:
adata_conc.write_h5ad(s_path+"Tissue_or_Nonimmune/GSE176308_Nanus_2021_Fibroblast.h5ad")

In [11]:
adata_conc.obs.disease.value_counts()

Osteoarthritis    4248
Name: disease, dtype: int64